version: '3.9'
services:
  postgres:
    container_name: postgres2
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DB: 'banks'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - '5433:5432'