flyway:
  url: jdbc:postgresql://localhost:5433/banks
  user: admin
  password: admin

datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5433/banks
  user: admin
  password: admin

